spring:
  application:
    name: gateway
server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
zuul:
  routes:
    common: /common/**
    eureka-consumer: /eureka-consumer/**